name: Remove Duplicate Jobs

on:
  workflow_dispatch:  # Manual trigger only
  schedule:
    - cron: '0 2 * * 0'  # Run every Sunday at 2 AM UTC

jobs:
  remove-duplicates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Remove duplicate jobs via Strapi API
        env:
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          STRAPI_INGEST_SECRET: ${{ secrets.STRAPI_INGEST_SECRET }}
        run: |
          echo "🔍 Triggering job deduplication via Strapi API..."
          echo "🔗 Endpoint: $STRAPI_URL/api/jobs/dedupe/trigger"
          
          response=$(curl -s -w "\n%{http_code}" \
            -H "x-seed-secret: $STRAPI_INGEST_SECRET" \
            "$STRAPI_URL/api/jobs/dedupe/trigger")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "📊 Response HTTP Status: $http_code"
          
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Deduplication completed successfully"
            if command -v jq &> /dev/null; then
              echo "$body" | jq '.'
            else
              echo "$body"
            fi
          else
            echo "❌ Deduplication failed with HTTP $http_code"
            echo "$body"
            exit 1
          fi
          
      - name: Report results
        if: always()
        run: |
          echo "Duplicate removal job completed"
          echo "Check the logs above for results"
