name: Seed ATS Terms

on:
  workflow_dispatch:
  push:
    paths:
      - 'seed/ats/*.json'

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Post each seed file
        env:
          ATS_API_URL: ${{ secrets.ATS_API_URL }}
          ATS_SEED_SECRET: ${{ secrets.ATS_SEED_SECRET }}
        run: |
          set -euo pipefail
          for f in seed/ats/*.json; do
            echo "Seeding $f"
            curl -fsSL -X POST "$ATS_API_URL/api/ats-terms/bulk" \
              -H "Content-Type: application/json" \
              -H "x-seed-secret: $ATS_SEED_SECRET" \
              --data-binary "@$f"
            echo ""
          done
