name: Seed ATS Terms
on:
  workflow_dispatch: {}   # run manually from GitHub Actions tab

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend
        uses: actions/checkout@v4

      - name: POST seed to Strapi
        run: |
          curl -sS -X POST "$ATS_API_URL/api/ats-terms/bulk" \
            -H "Content-Type: application/json" \
            -H "x-seed-secret: $ATS_SEED_SECRET" \
            --data-binary @seed/ats-terms.json
        env:
          ATS_API_URL: ${{ secrets.ATS_API_URL }}
          ATS_SEED_SECRET: ${{ secrets.ATS_SEED_SECRET }}
